---
title: Philanthropy Responds
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
    description: Posts
    feature_text: 'Welcome to the blog

'
    feature_image: assets/img/hero.jpeg
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
  values:
    image: "/assets/brand/lotus@1024px.png"
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jemoji
remote_theme: daviddarnes/alembic
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: magsonfire
author: PhilanthropyResponds
social:
  name: Philanthropy Responds
  links: 
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
css_inline: true
favicons:
  '16': "/assets/brand/lotus@16px.png"
  '32': "/assets/brand/lotus@32px.png"
  '96': "/assets/brand/lotus@96px.png"
  '120': "/assets/brand/lotus@120px.png"
  '144': "/assets/brand/lotus@144px.png"
  '180': "/assets/brand/lotus@180px.png"
  '512': "/assets/brand/lotus@512px.png"
  '1024': "/assets/brand/lotus@1024px.png"
navigation_header:
- title: Home
  url: "/"
- title: Collaborate
  url: "/collaborate/"
- title: Adapt
  url: "/adapt/"
- title: Participate
  url: "/participate/"
navigation_footer:
- title: Contribute your data
  url: "#"
