---
title: Philanthropy Responds
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
    description: Posts
    feature_text: 'Welcome to the blog

'
    feature_image: assets/img/hero.jpeg
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
  values:
    image: "/assets/brand/lotus@1024px.png"
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jemoji
remote_theme: daviddarnes/alembic
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: magsonfire
author: PhilanthropyResponds
social:
  name: Philanthropy Responds
  links: 
sass:
<<<<<<< HEAD
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Posts" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "assets/img/hero.jpeg"
  uploads:
    title: Uploads
    output: true

# 6. Jekyll collections settings
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ""
  values:
    image: "/assets/brand/lotus@1024px.png" # Default image for sharing

# 7. Site settings
# encoding: utf-8 # Make sure the encoding is right
# lang: en-CA # Set the site language
# title: "Philanthropy Responds" # Site name or title, also used in jekyll-seo-tag
# logo: "/assets/brand/Logo.svg" # Site logo, also used in jekyll-seo-tag
# description: "A website for Canadian philanthropy. # Site description and default description, also used in jekyll-seo-tag
# url: "https://philanthropyresponds.ca" # Site url, also used in jekyll-seo-tag
# baseurl: ""
# repo: "https://github.com/grantbookinc/philanthropy-responds"
# email: "hey@grantbook.org"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/brand/lotus@16px.png'
  32: '/assets/brand/lotus@32px.png'
  96: '/assets/brand/lotus@96px.png'
  120: '/assets/brand/lotus@120px.png'
  144: '/assets/brand/lotus@144px.png'
  180: '/assets/brand/lotus@180px.png'
  512: '/assets/brand/lotus@512px.png'
  1024: '/assets/brand/lotus@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Collaborate
  url: /collaborate/
- title: Adapt
  url: /adapt/
- title: Participate
  url: /participate/

navigation_footer:
- title: Contribute your data
  url: "#"
=======
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
css_inline: true
favicons:
  '16': "/assets/brand/lotus@16px.png"
  '32': "/assets/brand/lotus@32px.png"
  '96': "/assets/brand/lotus@96px.png"
  '120': "/assets/brand/lotus@120px.png"
  '144': "/assets/brand/lotus@144px.png"
  '180': "/assets/brand/lotus@180px.png"
  '512': "/assets/brand/lotus@512px.png"
  '1024': "/assets/brand/lotus@1024px.png"
>>>>>>> 76624995f154c2c85ec5b80aa978fff14676dff4
